### PR TITLE
Create requirements.md

### PR DESCRIPTION
**Pull request by guddbye**

### CODE REVIEW

**Comment by guddbye** [comment]
APPROVE ME PLEASE. I'M DESPERATE.

**Review by khofstetter94 — COMMENTED** [review]
looks good!

**Review by falashadegreene — APPROVED** [review]
Looks good ya'll!

**Review by Plaza-r — COMMENTED** [review]
Good work

**Review by Plaza-r — APPROVED** [review]

**Review by Plaza-r — APPROVED** [review]

**Pull request merged**
